spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cartdb
    username: cart
    password: cart

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
logging:
  level:
    org.flywaydb: debug